Feat/nav
salunkemanas/u-fit pull request #9
Opened 2024-10-13 16:44 UTC by salunkemanas

<img width="1470" alt="Screenshot 2024-10-13 at 10 13 47 PM" src="https://github.com/user-attachments/assets/b95aac8a-6624-496f-9b29-1c87bd9d6fdb">
Added fixed side and top navbar

2024-10-15 19:03 UTC, anandabhi04 requested changes

2024-10-15 19:03 UTC, anandabhi04 commented on src/app/layout.tsx
> +          <Stack className="size-full">
why h-full?

2024-10-15 19:03 UTC, anandabhi04 commented on src/app/layout.tsx
> +            <Stack className="w-5/6 p-3 overflow-auto h-[calc(100vh-65px)]">
overflow-y

2024-10-15 19:03 UTC, anandabhi04 commented on src/styles/components/ui/SideNav/SideNav.tsx
> +      className="bg-white size-full items-start shadow-md justify-center"
size-full?

2024-10-15 19:03 UTC, anandabhi04 commented on src/styles/components/ui/Stack/Stack.tsx
> +    gap: gap || undefined,
undefined?

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/SideNav/SideNav.tsx
> +  const navElements = [
move into useMemo

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/SideNav/SideNav.tsx
> +            <Icon className="size-5" />
@hatim-s todo: use semantic size

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/SideNav/SideNav.tsx
> +            {elem.name}
use Typography

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/SideNav/SideNav.tsx
> +          <Box
use stack

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/Stack/Stack.tsx
> +  // const gapClasses = cn(
remove

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/SideNav/SideNav.tsx
> +      gapY="md"
@hatim-s todo: remove gap from props and add semantic tokens

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/Stack/Stack.tsx
> +  const mergedClasses = twMerge(baseClass, className);
@hatim-s  todo: check if clsx should be used?

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/TopNav/TopNav.tsx
> +import { MagnifyingGlassIcon } from "@radix-ui/react-icons";
organize imports properly

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/TopNav/TopNav.tsx
> +      <Box className="font-bold text-lg">Logo</Box>
use typography, and use actual logo

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/TopNav/TopNav.tsx
> +        <MagnifyingGlassIcon className="ml-2" />
see if margin can be avoided

2024-10-27 14:15 UTC, hatim-s commented on src/styles/components/ui/TopNav/TopNav.tsx
> +        <AvatarFallback>CN</AvatarFallback>
use typograpphy

2024-10-27 14:15 UTC, hatim-s commented on src/app/layout.tsx
> +          <Box className="h-20 w-full fixed top-0 left-0 z-50 bg-white border-b">
@hatim-s todo add themes

2024-10-27 14:15 UTC, hatim-s commented on src/app/layout.tsx
> +          <Box className="h-20 w-full fixed top-0 left-0 z-50 bg-white border-b">
this is done partially with #10

2024-10-31 20:32 UTC, hatim-s approved these changes

2024-10-31 20:33 UTC, merged